cflags = -Wall -Werror -std=c99 -O2 -c
dflags = -Wall -Werror-std=c99 -g
sourceNodo = ../nodos/nodoarbol.o
includes = -I ../pila
source = $(wildcard *.c)
source_o = $(wildcard *.o)
output = ../../../lib/libArbol.a

build :
	gcc $(cflags) $(source) $(includes)
	ar rcs $(output) $(source_o) $(sourceNodo) 
	@echo "Compilo Exitosamente!!!"